spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dataeasev201?autoReconnect=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    #url: jdbc:mysql://localhost:3306/dataease0312?autoReconnect=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: pass
#    url: jdbc:mysql://172.16.2.14:3306/dataease?autoReconnect=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
#    username: hbgw_szyg
#    password: FW$FK1bKy
  messages:
    basename: i18n/lic,i18n/core,i18n/permissions,i18n/xpack,i18n/sync
  flyway:
    enabled: true
    table: de_standalone_version
    validate-on-migrate: false
    locations: classpath:db/migration
    baseline-on-migrate: true
    out-of-order: true

mybatis-plus:
  mapper-locations: classpath:mybatis/*.xml

cache:
  link:
    expire: 2  # refresh 刷新的有效时间（分钟）
  info:
    expire: 30  #findById的有效时间（分钟）
  data:
    expire: 30  #getData的有效时间（分钟）

